#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# load colors
. ~/.config/colors
 
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         5
bspc config window_gap           0

bspc config focused_border_color "$FOCUSED_BORDER"
bspc config normal_border_color  "$NORMAL_BORDER"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a "*:*:pygletcraft" state=floating center=on
bspc rule -a python3 state=floating
