term=foot
title=foot

#font=Cartograph Mono CF:size=14
#font=ProFont IIx Nerd Font:size=12
#font=CaskaydiaCove NF:size=14
#font=MapleMono NF Medium:size=14
#font=IBM EGA 8x14:size=19
#font=Departure Mono:size=14
#font=Terminess Nerd Font:size=14
#font=GohuFont 11 Nerd Font:size=13
#font=GohuFont 14 Nerd Font:size=13
#font=JetBrains Mono NF:size=14
#font=IBM VGA 8x16:size=19
#font=IBM Plex Mono:size=14
#font=NotoMono NF:size=14
#font=Monocraft:size=13

font=B612 Mono:size=12
font=Iosevka Nerd Font:size=12

pad=8x8

dpi-aware=yes

[cursor]
style=beam

[colors]
alpha=1
background=0f0f0f
foreground=f4decd

# black
regular0 = 1e1f1e
bright0  = 3b403c

# red
regular1 = f16e65
bright1  = ef968f

# green
regular2 = 7ec97e
bright2  = a4daa4

# yellow
regular3 = ef934d
bright3  = f4b585

# blue
regular4 = 71b4d6
bright4  = b0d4e8

# magenta
regular5 = e28dc6
bright5  = ebadd6

# cyan
regular6 = 7ec9a3
bright6  = abd4bf

# white
regular7 = d9cdb5
bright7  = f4decd

[key-bindings]
clipboard-copy=Control+c
clipboard-paste=Control+v

[text-bindings]
\x03=Control+Shift+c
